Imports System.IO
Imports System.Timers
Imports Timer = System.Timers.Timer
Public Class Form1
    Public Shared numberOfThreats As Integer = 0
    Public Shared ransomwareString As String = RandomString(6, 10)

    Private checkRansomware As New Object
    Dim ransomwareAlert As Boolean = False
    Dim oneTimer As Timer = New Timer()
    Dim path As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments & "\" & Form1.ransomwareString
    Dim di As IO.DirectoryInfo = New IO.DirectoryInfo(path)
    Dim content As String = "Dear User," & Environment.NewLine & "This file has been generated by PCNukerPro as a honeypot for Ransomwares, do not edit it nor delete it." &
        Environment.NewLine & "Don't edit also all the other files in this folder!" & Environment.NewLine & "Thanks for your collaboration"

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        System.Windows.Forms.Control.CheckForIllegalCrossThreadCalls = False
        loadPCInfo()
    End Sub

    Private Sub cleanbutton_Click(sender As Object, e As EventArgs) Handles cleanbutton.Click
        If tempcheckbox.Checked = True Then
            Try
                CleanTemp()
                CleanAppDataTemp()
            Catch
            End Try
        End If
        If prefetchcheckbox.Checked = True Then
            Try
                CleanPrefetch()
            Catch
            End Try
        End If
        If javacachecheckbox.Checked = True Then
            Try
                CleanJava()
            Catch
            End Try
        End If
        If recyclebincheckbox.Checked = True Then
            Try
                EmptyRecycleBin()
            Catch
            End Try
        End If
        AddItem2Listbox("Junk Files Cleaning Finished at " & DateTime.Now.ToString("HH:mm:ss"))
    End Sub

    Private Sub sfcbutton_Click(sender As Object, e As EventArgs) Handles sfcbutton.Click
        SFC()
        AddItem2Listbox("SFC Scannow Started at " & DateTime.Now.ToString("HH:mm:ss"))
    End Sub

    Private Sub chkdsk_Click(sender As Object, e As EventArgs) Handles chkdsk.Click
        CHKDSKK()
        AddItem2Listbox("CHKDSK Started at " & DateTime.Now.ToString("HH:mm:ss"))
    End Sub

    Private Sub dismscan_Click(sender As Object, e As EventArgs) Handles dismscan.Click
        DISMScann()
        AddItem2Listbox("DISM Scan Started at " & DateTime.Now.ToString("HH:mm:ss"))
    End Sub

    Private Sub dismrestore_Click(sender As Object, e As EventArgs) Handles dismrestore.Click
        DISMRestoree()
        AddItem2Listbox("DISM Restore Healt Started at " & DateTime.Now.ToString("HH:mm:ss"))
    End Sub

    Private Sub AddItem2Listbox(ByVal item As String)
        LogsListbox.Items.Add(item)
        LogsListbox.TopIndex = LogsListbox.Items.Count - 1
    End Sub

    Private Sub quickscanbutton_Click(sender As Object, e As EventArgs) Handles quickscanbutton.Click
        'VBC Scanner
        AddItem2Listbox("VBC Scan Started at " & DateTime.Now.ToString("HH:mm:ss"))
        If vbcprocess() = True Then
            numberOfThreats += 1
            AddItem2Listbox("vbc process found, you are infected with DarkCometRAT or other Trojans")
        Else
            AddItem2Listbox("Your system seems clear from vbc infection")
        End If
        'QuickMalwareHunter Scan
        AddItem2Listbox("Quick Malware Hunter Started at " & DateTime.Now.ToString("HH:mm:ss"))
        QuickMalwareHunter()
        'SmartMalwareHunter Scan
        AddItem2Listbox("Smart Malware Hunter Started at " & DateTime.Now.ToString("HH:mm:ss"))
        SmartMalwareHunter()

        AddItem2Listbox("Full System Malware Scan Terminated at " & DateTime.Now.ToString("HH:mm:ss") & " with " & numberOfThreats.ToString & " threats")

        If numberOfThreats > 0 Then
            MsgBox("Scan found " & numberOfThreats.ToString & " viruses in your system. Please check the log board for further details.", MsgBoxStyle.Critical, "VIRUSES FOUND!")
        End If
        numberOfThreats = 0
    End Sub

    Private Sub startupscanbutton_Click(sender As Object, e As EventArgs) Handles startupscanbutton.Click
        AddItem2Listbox("Startup Scan Started at " & DateTime.Now.ToString("HH:mm:ss"))
        'shellstartup scan
        StartupFolderScan()
        'startupscan regedit
        StartupRegistryScanLM()
        StartupRegistryScanCU()
        StartupRegistryScanWow64LM()
        StartupWMIService()

        AddItem2Listbox("Startup Malware Scan Terminated at " & DateTime.Now.ToString("HH:mm:ss") & " with " & numberOfThreats.ToString & " threats")

        If numberOfThreats > 0 Then
            MsgBox("Scan found " & numberOfThreats.ToString & " viruses in your Startup. Please check the log board for further details.", MsgBoxStyle.Critical, "VIRUSES FOUND!")
        End If
        numberOfThreats = 0
    End Sub

    Private Sub startransomware_Click(sender As Object, e As EventArgs) Handles startransomware.Click
        stopransomware.Enabled = True
        startransomware.Enabled = False
        ransomware.Text = My.Computer.FileSystem.SpecialDirectories.MyDocuments & "\" & Form1.ransomwareString & " is being monitored"
        startAntiRansomware()
    End Sub

    Private Sub stopransomware_Click(sender As Object, e As EventArgs) Handles stopransomware.Click
        startransomware.Enabled = True
        stopransomware.Enabled = False
        ransomware.Text = "Ransomware Status: OFF"
        stopAntiRansomware()
    End Sub

    Public Sub startAntiRansomware()
        If Not My.Computer.FileSystem.DirectoryExists(path) Then
            My.Computer.FileSystem.CreateDirectory(path)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".txt", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".doc", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".docx", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".xlsx", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".xls", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".ppt", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".pptx", content)
            File.WriteAllText(path & "\" & RandomString(4, 15) & ".pdf", content)
        End If
        makeTimers()
    End Sub

    Public Sub stopAntiRansomware()
        oneTimer.Enabled = False
        If My.Computer.FileSystem.DirectoryExists(path) Then
            Try
                'My.Computer.FileSystem.DeleteDirectory(path, FileIO.DeleteDirectoryOption.DeleteAllContents, FileIO.RecycleOption.DeletePermanently)
                System.IO.Directory.Delete(path, True)
            Catch ex As Exception
                MsgBox(ex.ToString)
            End Try
        End If
    End Sub

    Public Sub makeTimers() 'gotta keep them here in order to avoid problems with delgate
        oneTimer.Interval = 1000
        AddHandler oneTimer.Elapsed, AddressOf oneTimerEvent
        oneTimer.AutoReset = True
        oneTimer.Enabled = True
    End Sub
    Public Sub oneTimerEvent(ByVal source As Object, ByVal e As ElapsedEventArgs)
        For Each honeypot As IO.FileInfo In di.GetFiles()
            SyncLock checkRansomware
                Try
                    If Not File.ReadAllText(honeypot.FullName).Contains("PCNukerPro") Then
                        ransomwareAlert = True
                    End If
                    If honeypot.ToString.Contains(".exe") Then
                        ransomwareAlert = True
                    End If
                Catch
                End Try
            End SyncLock
        Next

        If ransomwareAlert = True Then
            itsAlertTime() 'checks all the checkboxes for the reaction settings that have been setupped
        End If

    End Sub
    Public Sub itsAlertTime()
        LogsListbox.Items.Add(DateTime.Now.ToString("HH:mm:ss") & " - " & "AntiRansomware Monitor has detected a suspicious behaviour")
        oneTimer.Enabled = False
        startransomware.Enabled = True
        stopransomware.Enabled = False

        If shutdowncheckbox.Checked = False And setvaultscheckbox.Checked = False Then
            MsgBox("AntiRansomware Monitor has detected a suspicious behaviour, please take actions as soon as possible." &
                   "If you are not part of the IT Team shut down immediately this PC and call your supervisor or manager.", MsgBoxStyle.Critical, "AntiRansomware suspicious behaviour")
        End If

        If setvaultscheckbox.Checked = True Then

        End If

        If shutdowncheckbox.Checked = True Then

        End If

    End Sub
End Class

