'Imports System.IO
'Imports System.Timers
'Imports Timer = System.Timers.Timer

'Module AntiRansomware
'    Private checkRansomware As New Object
'    Dim ransomwareAlert As Boolean = False
'    Dim oneTimer As Timer = New Timer()
'    Dim path As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments & "\" & Form1.ransomwareString
'    Dim di As IO.DirectoryInfo = New IO.DirectoryInfo(path)
'    Dim content As String = "Dear User," & Environment.NewLine & "This file has been generated by PCNukerPro as a honeypot for Ransomwares, do not edit it nor delete it." &
'        Environment.NewLine & "Don't edit also all the other files in this folder!" & Environment.NewLine & "Thanks for your collaboration"
'    Public Sub startAntiRansomware()
'        If Not My.Computer.FileSystem.DirectoryExists(path) Then
'            My.Computer.FileSystem.CreateDirectory(path)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".txt", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".doc", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".docx", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".xlsx", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".xls", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".ppt", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".pptx", content)
'            File.WriteAllText(path & "\" & RandomString(4, 15) & ".pdf", content)
'        End If
'        makeTimers()
'    End Sub

'    Public Sub stopAntiRansomware()
'        oneTimer.Enabled = False
'        If My.Computer.FileSystem.DirectoryExists(path) Then
'            Try
'                'My.Computer.FileSystem.DeleteDirectory(path, FileIO.DeleteDirectoryOption.DeleteAllContents, FileIO.RecycleOption.DeletePermanently)
'                System.IO.Directory.Delete(path, True)
'            Catch ex As Exception
'                MsgBox(ex.ToString)
'            End Try
'        End If
'    End Sub

'    Public Sub makeTimers()
'        oneTimer.Interval = 1000
'        AddHandler oneTimer.Elapsed, AddressOf oneTimerEvent
'        oneTimer.AutoReset = True
'        oneTimer.Enabled = True
'    End Sub
'    Public Sub oneTimerEvent(ByVal source As Object, ByVal e As ElapsedEventArgs)
'        For Each honeypot As IO.FileInfo In di.GetFiles()
'            SyncLock checkRansomware
'                Try
'                    If Not File.ReadAllText(honeypot.FullName).Contains("PCNukerPro") Then
'                        ransomwareAlert = True
'                    End If
'                    If honeypot.ToString.Contains(".exe") Then
'                        ransomwareAlert = True
'                    End If
'                Catch
'                End Try

'                If ransomwareAlert = True Then
'                    itsAlertTime() 'checks all the checkboxes for the reaction settings that have been setupped
'                End If
'            End SyncLock
'        Next


'    End Sub
'    Public Sub itsAlertTime()
'        'Form1.LogsListbox.Items.Add(DateTime.Now.ToString("HH:mm:ss") & " - " & "AntiRansomware Monitor has detected a suspicious behaviour")
'    End Sub
'End Module
