'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PCNukerPro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a the
        '''of
        '''to
        '''and
        '''in
        '''is
        '''it
        '''you
        '''that
        '''he
        '''was
        '''for
        '''on
        '''are
        '''with
        '''as
        '''his
        '''they
        '''be
        '''at
        '''one
        '''have
        '''this
        '''from
        '''or
        '''had
        '''by
        '''hot
        '''word
        '''but
        '''what
        '''some
        '''we
        '''can
        '''out
        '''other
        '''were
        '''all
        '''there
        '''when
        '''up
        '''use
        '''your
        '''how
        '''said
        '''an
        '''each
        '''she
        '''which
        '''do
        '''their
        '''time
        '''if
        '''will
        '''way
        '''about
        '''many
        '''then
        '''them
        '''write
        '''would
        '''like
        '''so
        '''these
        '''her
        '''long
        '''make
        '''thing
        '''see
        '''him
        '''two
        '''has
        '''look
        '''more
        '''day
        '''could
        '''go
        '''come
        '''did
        '''number
        '''sound
        '''no
        '''most
        '''people
        '''my
        '''over
        '''know
        '''water
        '''than
        '''call
        '''first
        '''who
        '''may
        '''side
        ''' [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property englishwords() As String
            Get
                Return ResourceManager.GetString("englishwords", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
